name: Daily Hadith Reel

on:
  schedule:
    - cron: '0 12 * * *'  # 12 PM UTC every day
  workflow_dispatch:

jobs:
  generate-and-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg fonts-noto

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load session data
      uses: actions/download-artifact@v3
      with:
        name: instagram-session
        path: .

    - name: Run Hadith Bot
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      run: |
        python main.py

    - name: Save session data
      uses: actions/upload-artifact@v3
      with:
        name: instagram-session
        path: |
          *_uuid_and_cookie.json
        retention-days: 7
